name = "gprbuild"
version = "22.0.1"
description = "The GPRBuild Ada/multilanguage build tool"
maintainers = ["chouteau@adacore.com"]
maintainers-logins = ["Fabien-Chouteau"]

auto-gpr-with = false

[environment]
PATH.prepend = "${CRATE_ROOT}/bin"

[configuration]
disabled = true

[origin."case(os)".linux."case(host-arch)".aarch64]
url = "https://github.com/reznikmm/GNAT-FSF-builds/releases/download/gprbuild-22.0.0-1/gprbuild-aarch64-linux-22.0.0-1.tar.gz"
hashes = ["sha256:19730c52a46c32f0f2f4a295418762a0e22645ef663f2a1c1f1b77ea71a4cee4"]
